# Generated by Django 4.0.5 on 2022-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Name')),
                ('department', models.CharField(choices=[{'mechanical', 'Mechanical'}, {'Electrical', 'electrical'}, {'Computers', 'computers'}, {'Electronics', 'electronics'}, {'Civil', 'civil'}, {'fill-choice', 'Fill-Choice'}], default='fill-choice', max_length=50, verbose_name='Department')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('mobile', models.IntegerField(verbose_name='Mobile No')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Updated At')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
