# Generated by Django 4.0.5 on 2022-06-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('mechanical', 'Mechanical'), ('electrical', 'Electrical'), ('computers', 'Computers'), ('electronics', 'Electronics'), ('civil', 'Civil')], max_length=50, verbose_name='Department'),
        ),
    ]
